"use client";
import { useEffect,useState } from "react";

type Payment={id:string;amount:number;minutes:number;status:string;qrCode?:string;qrBase64?:string;ticketUrl?:string};
type Method="pix"|"cash";
async function apiPayload(response:Response){const raw=await response.text();try{return JSON.parse(raw)}catch{throw new Error(`Servidor respondeu ${response.status}: ${raw.slice(0,180)||"resposta vazia"}`)}}

export default function Comprar(){
 const[device,setDevice]=useState(""),[mac,setMac]=useState(""),[address,setAddress]=useState(""),[minutes,setMinutes]=useState(0),[price,setPrice]=useState<number|null>(null),[email,setEmail]=useState(""),[method,setMethod]=useState<Method|null>(null),[payment,setPayment]=useState<Payment|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(location.search),d=q.get("device")||"",m=q.get("mac")||"",ip=q.get("ip")||"",time=Number(q.get("minutes"));setDevice(d);setMac(m);setAddress(ip);setMinutes(time);fetch(`/api/payments/config/${time}`).then(apiPayload).then(p=>p.price?setPrice(p.price):setMessage(p.error||"Este plano ainda não possui preço configurado.")).catch(error=>setMessage(error instanceof Error?error.message:"Falha ao consultar o plano."))},[]);
 useEffect(()=>{if(!payment?.id||payment.status==="approved"||payment.status==="paid_cash")return;const check=async()=>{try{const r=await fetch(`/api/payments/status/${payment.id}`,{cache:"no-store"}),p=await apiPayload(r);if(!r.ok)throw new Error(p.error||"Falha ao consultar pagamento");if(p.released||p.status==="approved"||p.status==="paid_cash"){setPayment(current=>current?{...current,status:p.status}:current);setMessage("Pagamento aprovado! O acesso será liberado em até 15 segundos.")}}catch(error){setMessage(error instanceof Error?error.message:"Falha ao consultar pagamento.")}};const timer=setInterval(check,3000);return()=>clearInterval(timer)},[payment?.id,payment?.status]);
 async function createPix(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/payments/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deviceId:device,mac,address,minutes,email})}),p=await apiPayload(r);if(!r.ok)throw new Error([p.error,p.detail].filter(Boolean).join(": ")||"Não foi possível gerar o Pix.");setPayment(p);setMessage("Acesso temporário para pagamento liberado por 2 minutos.")}catch(error){setMessage(error instanceof Error?error.message:"Falha ao gerar Pix.")}finally{setBusy(false)}}
 async function requestCash(){setBusy(true);setMessage("");try{const r=await fetch("/api/payments/cash-request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deviceId:device,mac,minutes})}),p=await apiPayload(r);if(!r.ok)throw new Error(p.error||"Não foi possível registrar o pagamento em espécie.");setPayment(p);setMessage("Pedido enviado ao atendente. O acesso será liberado após a confirmação do recebimento.")}catch(error){setMessage(error instanceof Error?error.message:"Falha ao registrar o pedido.")}finally{setBusy(false)}}
 async function copy(){if(!payment?.qrCode)return;await navigator.clipboard.writeText(payment.qrCode);setMessage("Código Pix copiado.")}
 const summary=<div className="payment-summary"><b>{minutes||"—"} minutos de Wi-Fi</b><strong>{price===null?"—":price.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></div>;
 return <main className="payment-shell"><section className="payment-card"><div className="payment-brand">Conecta<span>+</span></div>{payment?.status==="approved"||payment?.status==="paid_cash"?<div className="payment-approved"><span>✓</span><h1>Pagamento aprovado</h1><p>Sua liberação foi enviada ao MikroTik. Aguarde alguns segundos e tente acessar a internet.</p></div>:payment?.status==="cash_pending"?<div className="cash-waiting"><span className="eyebrow">PAGAMENTO EM ESPÉCIE</span><h1>Aguardando o atendente</h1>{summary}<p>Dirija-se ao atendente para realizar o pagamento. Nenhuma cobrança Pix foi criada.</p></div>:payment&&method==="pix"?<><span className="eyebrow">PIX MERCADO PAGO</span><h1>Escaneie para pagar</h1>{summary}{payment.qrBase64&&<img className="pix-qr" src={`data:image/png;base64,${payment.qrBase64}`} alt="QR Code Pix"/>}<label className="pix-code-label">PIX COPIA E COLA<textarea readOnly value={payment.qrCode}/></label><button className="pix-copy" onClick={copy}>Copiar código Pix</button><small>Aguardando confirmação automática do Mercado Pago...</small></>:method==="pix"?<form onSubmit={createPix}><span className="eyebrow">PAGAMENTO VIA PIX</span><h1>Finalize com Pix</h1>{summary}<label>E-MAIL DO PAGADOR<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@exemplo.com"/></label><button disabled={busy||price===null}>{busy?"Gerando QR Code...":"Gerar QR Code Pix"}</button><button type="button" className="payment-back" onClick={()=>setMethod(null)}>Voltar</button></form>:<><span className="eyebrow">FORMA DE PAGAMENTO</span><h1>Como deseja pagar?</h1>{summary}<div className="payment-methods"><button disabled={busy||price===null} onClick={()=>setMethod("pix")}><strong>Pix</strong><small>QR Code pelo Mercado Pago</small></button><button disabled={busy||price===null} onClick={()=>{setMethod("cash");requestCash()}}><strong>Em espécie</strong><small>Pague diretamente ao atendente</small></button></div></>}{message&&<div className="payment-message">{message}</div>}<footer>{method==="pix"?"Pagamento processado com segurança pelo Mercado Pago":"Conecta+ · Acesso Wi-Fi"}</footer></section></main>;
}
