"use client";
import { useEffect,useState } from "react";
type Pix={id:string;amount:number;minutes:number;status:string;qrCode:string;qrBase64:string;ticketUrl:string};
export default function Comprar(){const[device,setDevice]=useState(""),[mac,setMac]=useState(""),[minutes,setMinutes]=useState(0),[price,setPrice]=useState<number|null>(null),[email,setEmail]=useState(""),[pix,setPix]=useState<Pix|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const q=new URLSearchParams(location.search),d=q.get("device")||"",m=q.get("mac")||"",time=Number(q.get("minutes"));setDevice(d);setMac(m);setMinutes(time);fetch(`/api/payments/config/${time}`).then(r=>r.json()).then(p=>p.price?setPrice(p.price):setMessage("Este plano ainda não possui preço configurado."))},[]);
 useEffect(()=>{if(!pix?.id||pix.status==="approved")return;const check=async()=>{const r=await fetch(`/api/payments/status/${pix.id}`,{cache:"no-store"}),p=await r.json();if(p.status==="approved"){setPix(current=>current?{...current,status:"approved"}:current);setMessage("Pagamento aprovado! O acesso será liberado em até 15 segundos.")}};const timer=setInterval(check,3000);return()=>clearInterval(timer)},[pix?.id,pix?.status]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/payments/create",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deviceId:device,mac,minutes,email})}),p=await r.json();if(!r.ok)throw new Error(p.error||"Não foi possível gerar o Pix.");setPix(p)}catch(error){setMessage(error instanceof Error?error.message:"Falha ao gerar Pix.")}finally{setBusy(false)}}
 async function copy(){if(!pix?.qrCode)return;await navigator.clipboard.writeText(pix.qrCode);setMessage("Código Pix copiado.")}
 return <main className="payment-shell"><section className="payment-card"><div className="payment-brand">Conecta<span>+</span></div>{pix?.status==="approved"?<div className="payment-approved"><span>✓</span><h1>Pagamento aprovado</h1><p>Sua liberação foi enviada ao MikroTik. Aguarde alguns segundos e tente acessar a internet.</p></div>:pix?<><span className="eyebrow">PIX MERCADO PAGO</span><h1>Escaneie para pagar</h1><div className="payment-summary"><b>{minutes} minutos de Wi-Fi</b><strong>{price?.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></div>{pix.qrBase64&&<img className="pix-qr" src={`data:image/png;base64,${pix.qrBase64}`} alt="QR Code Pix"/>}<button className="pix-copy" onClick={copy}>Copiar código Pix</button><small>Aguardando confirmação automática do Mercado Pago...</small></>:<form onSubmit={create}><span className="eyebrow">ACESSO WI-FI</span><h1>Finalize com Pix</h1><div className="payment-summary"><b>{minutes||"—"} minutos de Wi-Fi</b><strong>{price===null?"—":price.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></div><label>E-MAIL DO PAGADOR<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@exemplo.com"/></label><button disabled={busy||price===null}>{busy?"Gerando QR Code...":"Gerar QR Code Pix"}</button></form>}{message&&<div className="payment-message">{message}</div>}<footer>Pagamento processado com segurança pelo Mercado Pago</footer></section></main>}
