"use client";
import { useEffect,useState } from "react";
type Device={id:string;identity:string;model:string;mode:string;active_count:number|null;host_count:number|null;updated_at:string|null};
type Dashboard={device:Device;sessions:Array<{username:string;address:string;mac:string;uptime:string;time_left:string}>;hosts:Array<{address:string;mac:string;authorized:number}>;releases:Array<{id:string;mac:string;minutes:number;status:string;created_at:string}>};
export default function Gestao(){const[auth,setAuth]=useState(false),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[devices,setDevices]=useState<Device[]>([]),[selected,setSelected]=useState(""),[data,setData]=useState<Dashboard|null>(null),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/operations/devices",{cache:"no-store"});if(!r.ok)return;const p=await r.json();setAuth(true);setDevices(p.devices);if(!selected&&p.devices[0])setSelected(p.devices[0].id)}
 useEffect(()=>{fetch("/api/operations/session").then(r=>r.json()).then(p=>{if(p.authenticated){setAuth(true);load()}})},[]);
 useEffect(()=>{if(!selected)return;const run=()=>fetch(`/api/operations/dashboard/${selected}`,{cache:"no-store"}).then(r=>r.json()).then(setData);run();const t=setInterval(run,10000);return()=>clearInterval(t)},[selected]);
 async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/operations/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});if(!r.ok)return setError("Usuário ou senha inválidos.");setAuth(true);load()}
 async function release(mac:string,minutes:number){await fetch(`/api/operations/release/${selected}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mac,minutes})});setError(`Liberação de ${minutes} minutos enviada para ${mac}.`)}
 if(!auth)return <main className="ops-login"><form onSubmit={login}><span className="brand-mark"><i/><i/><i/></span><span className="eyebrow">CONecta+ OPERAÇÃO</span><h1>Gerenciar acessos</h1><p>Entre com o usuário autorizado para este MikroTik.</p><label>USUÁRIO<input value={username} onChange={e=>setUsername(e.target.value)} autoFocus/></label><label>SENHA<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<small>{error}</small>}<button>Entrar →</button></form></main>;
 const d=data?.device;return <main className="ops-shell"><header><div className="brand"><span className="brand-mark"><i/><i/><i/></span><span>Conecta<span>+</span></span></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{devices.map(x=><option key={x.id} value={x.id}>{x.identity} · {x.model}</option>)}</select><span className={d?.updated_at?"ops-online":"ops-offline"}>● {d?.updated_at?"Telemetria recebida":"Sem telemetria"}</span></header><section className="ops-content"><div className="ops-title"><div><span className="eyebrow">PAINEL OPERACIONAL</span><h1>{d?.identity||"MikroTik"}</h1><p>Dados recebidos diretamente do HotSpot.</p></div><b>{d?.mode==="admin"?"Liberação pelo administrador":"Visitante escolhe o tempo"}</b></div><div className="ops-stats"><article><small>CONECTADOS AGORA</small><strong>{d?.active_count??0}</strong></article><article><small>AGUARDANDO</small><strong>{d?.host_count??0}</strong></article><article><small>ÚLTIMA TELEMETRIA</small><strong className="date-stat">{d?.updated_at?new Date(d.updated_at).toLocaleTimeString("pt-BR"):"Sem dados"}</strong></article></div>{error&&<div className="ops-message">{error}</div>}{d?.mode==="admin"&&<article className="ops-card"><h2>Dispositivos aguardando liberação</h2>{!data?.hosts.length?<p className="empty">Nenhum dispositivo aguardando.</p>:data.hosts.filter(h=>!h.authorized).map(h=><div className="pending-row" key={h.mac}><div><strong>{h.mac||"MAC não informado"}</strong><small>{h.address}</small></div><div>{[5,10,15,30,60].map(m=><button key={m} onClick={()=>release(h.mac,m)}>{m} min</button>)}</div></div>)}</article>}<article className="ops-card"><h2>Sessões ativas</h2>{!data?.sessions.length?<p className="empty">Nenhuma sessão ativa recebida.</p>:data.sessions.map(s=><div className="active-row" key={`${s.mac}-${s.username}`}><strong>{s.username||s.mac}</strong><span>{s.address}</span><span>{s.uptime||"—"}</span><span>{s.time_left||"—"}</span></div>)}</article><article className="ops-card"><h2>Histórico real de liberações</h2>{!data?.releases.length?<p className="empty">Nenhuma liberação registrada.</p>:data.releases.map(r=><div className="active-row" key={r.id}><strong>{r.mac}</strong><span>{r.minutes} minutos</span><span>{r.status}</span><span>{new Date(r.created_at).toLocaleString("pt-BR")}</span></div>)}</article></section></main>}
