import { createCipheriv,createDecipheriv,createHash,randomBytes,randomUUID } from "node:crypto";
import { database as db } from "./database";
import { queuePaymentWindow, queueRelease } from "./operations-store";

db.exec(`CREATE TABLE IF NOT EXISTS pix_payments (id TEXT PRIMARY KEY,device_id TEXT NOT NULL,mac TEXT NOT NULL,minutes INTEGER NOT NULL,amount REAL NOT NULL,email TEXT NOT NULL,mp_payment_id TEXT,status TEXT NOT NULL,qr_code TEXT,qr_base64 TEXT,ticket_url TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,released INTEGER NOT NULL DEFAULT 0)`);
db.exec(`CREATE TABLE IF NOT EXISTS payment_settings (id INTEGER PRIMARY KEY CHECK(id=1),encrypted_json TEXT NOT NULL,updated_at TEXT NOT NULL)`);
const paymentColumns=db.prepare("PRAGMA table_info(pix_payments)").all() as Array<{name:string}>;
if(!paymentColumns.some(column=>column.name==="last_error"))try{db.exec("ALTER TABLE pix_payments ADD COLUMN last_error TEXT")}catch(error){if(!(error instanceof Error)||!error.message.includes("duplicate column name"))throw error}
if(!paymentColumns.some(column=>column.name==="release_id"))try{db.exec("ALTER TABLE pix_payments ADD COLUMN release_id TEXT")}catch(error){if(!(error instanceof Error)||!error.message.includes("duplicate column name"))throw error}
db.prepare("UPDATE pix_payments SET status='released',updated_at=? WHERE released=1 AND status IN ('creating','pending','in_process')").run(new Date().toISOString());
const now=()=>new Date().toISOString();
type PaymentSettings={accessToken:string;webhookSecret:string;prices:Record<string,number>};
const settingsKey=()=>createHash("sha256").update(process.env.ADMIN_SESSION_SECRET||process.env.ACTIVATION_TOKEN_SECRET||"development-settings-key").digest();
function encryptSettings(value:PaymentSettings){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",settingsKey(),iv),encrypted=Buffer.concat([cipher.update(JSON.stringify(value),"utf8"),cipher.final()]);return`${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`}
function decryptSettings(value:string){try{const[iv,tag,data]=value.split("."),decipher=createDecipheriv("aes-256-gcm",settingsKey(),Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(data,"base64url")),decipher.final()]).toString("utf8")) as PaymentSettings}catch{return null}}
function storedSettings(){const row=db.prepare("SELECT encrypted_json FROM payment_settings WHERE id=1").get() as {encrypted_json:string}|undefined;return row?decryptSettings(row.encrypted_json):null}
export function paymentAccessToken(){return storedSettings()?.accessToken||process.env.MERCADO_PAGO_ACCESS_TOKEN||""}
export function paymentWebhookSecret(){return storedSettings()?.webhookSecret||process.env.MERCADO_PAGO_WEBHOOK_SECRET||""}
export function paymentSettingsSummary(){const settings=storedSettings();return{configured:!!(settings?.accessToken||process.env.MERCADO_PAGO_ACCESS_TOKEN),accessTokenMasked:settings?.accessToken?`${settings.accessToken.slice(0,8)}••••${settings.accessToken.slice(-4)}`:process.env.MERCADO_PAGO_ACCESS_TOKEN?"Configurado pela variável de ambiente":"",webhookConfigured:!!(settings?.webhookSecret||process.env.MERCADO_PAGO_WEBHOOK_SECRET),prices:Object.fromEntries([5,10,15,30,60].map(minutes=>[minutes,priceFor(minutes)||0])),source:settings?"database":"environment"}}
export function savePaymentSettings(input:{accessToken?:string;webhookSecret?:string;prices?:Record<string,unknown>}){const current=storedSettings(),accessToken=String(input.accessToken||"").trim()||current?.accessToken||"",webhookSecret=String(input.webhookSecret||"").trim()||current?.webhookSecret||"";if(accessToken.length<20||webhookSecret.length<16)throw new Error("Credenciais inválidas");const prices=Object.fromEntries([5,10,15,30,60].map(minutes=>{const value=Number(input.prices?.[minutes]);if(!Number.isFinite(value)||value<=0||value>10000)throw new Error("Preço inválido");return[String(minutes),Number(value.toFixed(2))]}));db.prepare("INSERT INTO payment_settings(id,encrypted_json,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET encrypted_json=excluded.encrypted_json,updated_at=excluded.updated_at").run(encryptSettings({accessToken,webhookSecret,prices}),now());return paymentSettingsSummary()}

export function priceFor(minutes:number){if(![5,10,15,30,60].includes(minutes))return null;const value=Number(storedSettings()?.prices?.[String(minutes)]??process.env[`PIX_PRICE_${minutes}`]);return Number.isFinite(value)&&value>0?Number(value.toFixed(2)):null}
export function paymentDevice(deviceId:string){return db.prepare(`SELECT d.id,d.identity,a.mode FROM devices d JOIN activations a ON a.id=d.activation_id WHERE d.id=?`).get(deviceId) as {id:string;identity:string;mode:string}|undefined}
export function paymentClientAddress(deviceId:string,mac:string){const row=db.prepare(`SELECT address FROM hotspot_hosts WHERE device_id=? AND mac=? UNION ALL SELECT address FROM hotspot_sessions WHERE device_id=? AND mac=? LIMIT 1`).get(deviceId,mac,deviceId,mac) as {address:string}|undefined;return row?.address||""}
export function newPayment(deviceId:string,mac:string,minutes:number,amount:number,email:string){const id=randomUUID();db.prepare(`INSERT INTO pix_payments(id,device_id,mac,minutes,amount,email,status,created_at,updated_at,released) VALUES (?,?,?,?,?,?,'creating',?,?,0)`).run(id,deviceId,mac,minutes,amount,email,now(),now());return id}
export function newCashPayment(deviceId:string,mac:string,minutes:number,amount:number){const existing=db.prepare("SELECT id FROM pix_payments WHERE device_id=? AND mac=? AND status='cash_pending' AND released=0 ORDER BY created_at DESC LIMIT 1").get(deviceId,mac) as {id:string}|undefined;if(existing)return existing.id;const id=randomUUID();db.prepare(`INSERT INTO pix_payments(id,device_id,mac,minutes,amount,email,status,created_at,updated_at,released) VALUES (?,?,?,?,?,'','cash_pending',?,?,0)`).run(id,deviceId,mac,minutes,amount,now(),now());return id}
export function saveMercadoPago(id:string,p:any){db.prepare(`UPDATE pix_payments SET mp_payment_id=?,status=?,qr_code=?,qr_base64=?,ticket_url=?,last_error=NULL,updated_at=? WHERE id=?`).run(String(p.id),String(p.status||"pending"),p.point_of_interaction?.transaction_data?.qr_code||"",p.point_of_interaction?.transaction_data?.qr_code_base64||"",p.point_of_interaction?.transaction_data?.ticket_url||"",now(),id)}
export function failPayment(id:string,error="Falha não identificada",status="error"){db.prepare("UPDATE pix_payments SET status=?,last_error=?,updated_at=? WHERE id=?").run(status,String(error).slice(0,1000),now(),id)}
export function getPayment(id:string){return db.prepare("SELECT * FROM pix_payments WHERE id=?").get(id) as any}
export function paymentByMpId(mpId:string){return db.prepare("SELECT * FROM pix_payments WHERE mp_payment_id=?").get(mpId) as any}
function ensureRelease(payment:any,actor:string){if(payment.release_id)return payment.release_id as string;const existing=db.prepare("SELECT id FROM access_releases WHERE device_id=? AND mac=? AND created_by=? AND datetime(created_at)>=datetime(?) ORDER BY created_at DESC LIMIT 1").get(payment.device_id,payment.mac,actor,payment.created_at) as {id:string}|undefined;const releaseId=existing?.id||queueRelease(payment.device_id,payment.mac,Number(payment.minutes),actor);if(releaseId)db.prepare("UPDATE pix_payments SET release_id=?,updated_at=? WHERE id=?").run(releaseId,now(),payment.id);return releaseId}
export function applyPaymentStatus(id:string,status:string){const current=getPayment(id);if(!current||current.status==="paid_cash")return;db.prepare("UPDATE pix_payments SET status=?,updated_at=? WHERE id=? AND status<>'paid_cash'").run(status,now(),id);if(status==="approved")ensureRelease({...current,status},"mercadopago")}
export function paymentDiagnostics(deviceId?:string){return deviceId?db.prepare(`SELECT p.id,p.device_id,p.mac,p.minutes,p.amount,p.status,p.released,p.mp_payment_id,p.last_error,p.created_at,p.updated_at,COALESCE(d.display_name,d.identity) identity FROM pix_payments p JOIN devices d ON d.id=p.device_id WHERE p.device_id=? ORDER BY p.created_at DESC LIMIT 50`).all(deviceId):db.prepare(`SELECT p.id,p.device_id,p.mac,p.minutes,p.amount,p.status,p.released,p.mp_payment_id,p.last_error,p.created_at,p.updated_at,COALESCE(d.display_name,d.identity) identity FROM pix_payments p JOIN devices d ON d.id=p.device_id ORDER BY p.created_at DESC LIMIT 50`).all()}

export function financialReport(days:number){
 const safeDays=[7,30,90].includes(days)?days:30,period=`-${safeDays} days`,confirmedSql="released=1";
 const summary=db.prepare(`SELECT COALESCE(SUM(CASE WHEN ${confirmedSql} THEN amount ELSE 0 END),0) gross_revenue,SUM(CASE WHEN ${confirmedSql} THEN 1 ELSE 0 END) confirmed_sales,COUNT(*) attempts,SUM(CASE WHEN status='cash_pending' THEN 1 ELSE 0 END) pending_cash,COALESCE(SUM(CASE WHEN status='cash_pending' THEN amount ELSE 0 END),0) pending_cash_amount,SUM(CASE WHEN status='error' THEN 1 ELSE 0 END) failures FROM pix_payments WHERE datetime(created_at)>=datetime('now',?)`).get(period) as any;
 const methods=db.prepare(`SELECT CASE WHEN mp_payment_id IS NOT NULL AND mp_payment_id<>'' THEN 'pix' ELSE 'cash' END method,COUNT(*) sales,COALESCE(SUM(amount),0) revenue FROM pix_payments WHERE ${confirmedSql} AND datetime(created_at)>=datetime('now',?) GROUP BY method ORDER BY revenue DESC`).all(period);
 const plans=db.prepare(`SELECT minutes,COUNT(*) attempts,SUM(CASE WHEN ${confirmedSql} THEN 1 ELSE 0 END) sales,COALESCE(SUM(CASE WHEN ${confirmedSql} THEN amount ELSE 0 END),0) revenue FROM pix_payments WHERE datetime(created_at)>=datetime('now',?) GROUP BY minutes ORDER BY minutes`).all(period);
 const daily=db.prepare(`SELECT date(created_at) day,COUNT(*) attempts,SUM(CASE WHEN ${confirmedSql} THEN 1 ELSE 0 END) sales,COALESCE(SUM(CASE WHEN ${confirmedSql} THEN amount ELSE 0 END),0) revenue FROM pix_payments WHERE datetime(created_at)>=datetime('now',?) GROUP BY date(created_at) ORDER BY day`).all(period);
 const devices=db.prepare(`SELECT d.id,COALESCE(d.display_name,d.identity) identity,COUNT(p.id) attempts,SUM(CASE WHEN p.released=1 THEN 1 ELSE 0 END) sales,COALESCE(SUM(CASE WHEN p.released=1 THEN p.amount ELSE 0 END),0) revenue FROM devices d LEFT JOIN pix_payments p ON p.device_id=d.id AND datetime(p.created_at)>=datetime('now',?) GROUP BY d.id,d.display_name,d.identity ORDER BY revenue DESC,COALESCE(d.display_name,d.identity)`).all(period);
 const statuses=db.prepare(`SELECT status,COUNT(*) total FROM pix_payments WHERE datetime(created_at)>=datetime('now',?) GROUP BY status ORDER BY total DESC`).all(period);
 const recent=db.prepare(`SELECT p.id,p.mac,p.minutes,p.amount,p.status,p.mp_payment_id,p.updated_at,COALESCE(d.display_name,d.identity) identity FROM pix_payments p JOIN devices d ON d.id=p.device_id WHERE p.released=1 AND datetime(p.created_at)>=datetime('now',?) ORDER BY p.updated_at DESC LIMIT 20`).all(period);
 const confirmedCount=Number(summary.confirmed_sales||0),attempts=Number(summary.attempts||0),grossRevenue=Number(summary.gross_revenue||0);
 return{days:safeDays,generatedAt:now(),summary:{grossRevenue,confirmedSales:confirmedCount,attempts,averageTicket:confirmedCount?grossRevenue/confirmedCount:0,conversionRate:attempts?confirmedCount/attempts*100:0,pendingCash:Number(summary.pending_cash||0),pendingCashAmount:Number(summary.pending_cash_amount||0),failures:Number(summary.failures||0)},methods,plans,daily,devices,statuses,recent};
}

export function approveCashPayment(id:string){const payment=getPayment(id);if(!payment)return false;if(payment.release_id)return true;const releaseId=ensureRelease(payment,"cash-admin");if(!releaseId)return false;db.prepare("UPDATE pix_payments SET status='paid_cash',last_error=NULL,updated_at=? WHERE id=?").run(now(),id);return true}
export function reopenPaymentWindow(id:string){const payment=getPayment(id);if(!payment||payment.released||!payment.mp_payment_id)return false;const address=paymentClientAddress(payment.device_id,payment.mac);if(!address)return false;return !!queuePaymentWindow(payment.device_id,address,payment.mac)}
