name: Validar Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      - name: Construir imagem
        run: docker build --tag conecta-mais-hotspot:test .
